name: Poulina SSO — CD

on:
  workflow_run:
    workflows: ["Poulina SSO — CI"]
    branches: [ main, develop ]
    types: [ completed ]
  
  workflow_dispatch:

env:
  REGISTRY: docker.io 
  IMAGE_NAME: hsinemt/poulina-sso-api 

jobs:
  docker-build-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Log in to Docker Hub 
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=sha-,format=short
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./API/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}